apiVersion: apps/v1
kind: Deployment
metadata:
  name: bikes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bikes
  template:
    metadata:
      labels:
        app: bikes
    spec:
      containers:
      - name: bikes-container
        image: 983441761380.dkr.ecr.eu-west-1.amazonaws.com/paololatella-bikes-ecr-repository:latest
        ports:
        - containerPort: 5000
