apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cars
  template:
    metadata:
      labels:
        app: cars
    spec:
      containers:
      - name: cars-container
        image: 983441761380.dkr.ecr.eu-west-1.amazonaws.com/paololatella-cars-ecr-repository:latest
        ports:
        - containerPort: 5000
